homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 43.6106
  longitude: 1.3347
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 185
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Paris

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor:
# Weather Prediction
  - platform: yr
  - platform: ha02
    i2c_port: 6
  - platform: grove_light
    port: 1

switch:
    - platform: mraa_gpio
      ports:
          6: 'chauffage'

climate:
  - platform: generic_thermostat
    name: Home
    heater: switch.chauffage
    target_sensor: sensor.temperature
    min_temp: 18
    max_temp: 27
    target_temp: 23
    min_cycle_duration:
      seconds: 60
